"""agregar imagen_url a prenda para vestidor virtual CU-14

Revision ID: 48665e082459
Revises: 0001
Create Date: 2026-09-07 20:55:51.660956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48665e082459'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prenda', sa.Column('imagen_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prenda', 'imagen_url')
    # ### end Alembic commands ###
