"""agregar columna respuesta a interaccion_ia

Revision ID: 66ccd7b5c445
Revises: 8047feee8615
Create Date: 2026-09-14 17:17:40.036482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ccd7b5c445'
down_revision: Union[str, None] = '8047feee8615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaccion_ia', sa.Column('respuesta', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interaccion_ia', 'respuesta')
    # ### end Alembic commands ###
