"""agregar login de proveedor y tabla de disponibilidad

Revision ID: 8047feee8615
Revises: 52ee8cd9e5ec
Create Date: 2026-09-14 16:31:22.662913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8047feee8615'
down_revision: Union[str, None] = '52ee8cd9e5ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disponibilidad_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prenda_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha_estimada', sa.Date(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prenda_id'], ['prenda.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_disponibilidad_prenda', 'disponibilidad_proveedor', ['prenda_id'], unique=False)
    op.add_column('proveedor', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'proveedor', ['usuario_id'])
    op.create_foreign_key(None, 'proveedor', 'usuario', ['usuario_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Seed del rol "Proveedor" (CU-33, CU-34), necesario para que un proveedor pueda iniciar sesión.
    op.execute("""
        INSERT INTO rol (nombre, descripcion, estado)
        SELECT 'Proveedor', 'Proveedor con acceso propio para registrar productos e informar disponibilidad', true
        WHERE NOT EXISTS (SELECT 1 FROM rol WHERE nombre = 'Proveedor')
    """)


def downgrade() -> None:
    op.execute("DELETE FROM rol WHERE nombre = 'Proveedor'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proveedor', type_='foreignkey')
    op.drop_constraint(None, 'proveedor', type_='unique')
    op.drop_column('proveedor', 'usuario_id')
    op.drop_index('idx_disponibilidad_prenda', table_name='disponibilidad_proveedor')
    op.drop_table('disponibilidad_proveedor')
    # ### end Alembic commands ###
